### ISSUE TITLE
Can not able to locate campaign.csv

### ISSUE THREAD

**Issue by dharmen001** [kinosal/predictor#2]
Can you please share the campaign.csv or campaign.sql to check the what columns you are using?

**Comment by kinosal** [comment]
Hi! Sorry for the late reply. You can find all columns used to build the model shown in my blog post in the sample data file: https://github.com/kinosal/predictor/blob/master/model/impressions.csv. Hope that helps!

**Comment by dharmen001** [comment]
Hey,

It's really nice to hear back from you.

You have used campaign.csv at the when you start building out the model. Can you please share that file or column list you pulled from PostgreSQL database.

Thanks, D

**Comment by kinosal** [comment]
Hey! You can load the 'impressions.csv' instead of the 'campaigns.csv' (replace it in training.train). Just make sure to use the desired - existing - 'output' column. The feature columns can be the same. I just noticed you might encounter an error when trimming though, so I've adjusted that function to be more robust. Best, Nik
